project:
  type: book
  title: HyperLabsArduino
book:
  title: "HyperLabsArduino"
  chapters:
    - index.qmd
    - Beginner.qmd
    - Intermediate.qmd
format:
  html:
    theme: darkly # bootstrap theme, you can change (flatly, journal, darkly, etc.)
    toc: true # adds a table of contents
    favicon: hyperlabs.png
