project:
  type: book

book:
  title: "HyperLabs Arduino"
  subtitle: "Workshop Resources & Example Code"
  favicon: hyperlabs.png
  repo-url: https://github.com/cartaR02/HyperLabsArduino
  repo-actions: [source, issue]
  chapters:
    - index.qmd
    - Beginner.qmd
    - Intermediate.qmd
  page-navigation: true
  search: true

format:
  html:
    theme:
      dark: [darkly, custom.scss]
    toc: true
    toc-depth: 3
    toc-title: "On this page"
    number-sections: false
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai
